language: cpp
os:
    - linux
    - osx
compiler:
    - clang
    - gcc
sudo: required
dist: trusty
install: true
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen qt5 ninja; fi
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo add-apt-repository -y ppa:beineri/opt-qt596-trusty; fi
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get -qq update; fi
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -y qt59base qt59tools ninja-build doxygen; fi
env:
    - CMAKE_PREFIX_PATH=/usr/local/opt/qt5:/opt/qt59
script:
    - mkdir build && pushd build && cmake -G "Ninja" .. && ninja && ninja test && ninja package
