version: '{build}'
branches:
    only:
        - release_work
environment:
    matrix:
        - TRACETOOL_ARCH: x86
        - TRACETOOL_ARCH: x64
matrix:
    fast_finish: true

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
    - cinst ninja doxygen.install

build_script:
    - call build.cmd %TRACETOOL_ARCH% %APPVEYOR_REPO_TAG%

test_script:
    - set
    - pushd build
    - ninja test
    - popd
