branches:
    only:
        - release_work
platform:
    - x86
    - x64
matrix:
    fast_finish: true
install:
    - cinst ninja doxygen.install
#    - call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
#    - set CMAKE_PREFIX_PATH=C:\Qt\5.9.5\msvc2015

build_script:
    - mkdir build 
    - cd build
    - cmake -G "Ninja" ..
    - ninja

test_script:
    - ninja test
