version: '{build}'
branches:
    only:
        - release_work
        - refs/tags/*
environment:
    matrix:
        - TRACETOOL_ARCH: x86
        - TRACETOOL_ARCH: x64
matrix:
    fast_finish: true

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\Program Files\doxygen\ -> appveyor.yml

install:
    - cinst ninja doxygen.install

build_script:
    - call build.cmd %TRACETOOL_ARCH% %APPVEYOR_REPO_TAG%

test_script:
    - call test.cmd

artifacts:
    path: 'build\tracelib-*.zip'

deploy:
    provider: GitHub
    artifact: /tracelib-.*zip/
    auth_token:
        secure: fpX60tGeFQagF3J67doUTlTM2Esqb80OUpY7ZN4Drf1Iy0nOLT41TpOSJ0kuBGsO
    on:
        APPVEYOR_REPO_TAG: true
